project_id = "cbwpghrkfvczjqzefvix"

[functions.digitopay-webhook]
verify_jwt = false

[functions.digitopay-deposit-webhook]
verify_jwt = false

[functions.digitopay-withdrawal-webhook]
verify_jwt = false

[functions.process-transaction]
verify_jwt = false